repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: shellcheck
      - id: tflint
        args:
          - "--config=__GIT_ROOT__/.tflint.hcl"
      - id: terraform-fmt
      - id: terraform-validate
      - id: terragrunt-hcl-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=5120"]
      - id: check-json
        exclude: "^.vscode/*"
      - id: pretty-format-json
        args: ["--autofix"]
      - id: mixed-line-ending
      - id: check-symlinks
